function app_summary(){
    curl 'http://localhost:50864/lefv202310092005/gurusearchui/typesys/8/App.Summary.js-client-browser.js?tier=FULL&bootstrapped&x=Console&x=Boxed%3Cstring%3E&x=Console.Prefs&x=UserBasicAuthFields&x=Cached&x=Restful&x=PersistableFetchable&x=Fetchable&x=PersistableGettable&x=Gettable&x=PersistableWritable&x=Writable&x=Upsertable&x=Creatable&x=PersistableEvaluatable&x=Evaluatable&x=PersistableRefreshable&x=PersistableImportable&x=Importable&x=PersistableExportable&x=Exportable&x=PkgListenResult&x=HttpHeaderName&x=EventStream&x=EventStream%3CPkg.Event%3E&x=PkgState&x=Jvm&x=TupleFieldType&x=JvmUsage&x=JvmMemUsage&x=JupyterHub&x=UiBundler&x=Extendable&x=UiBundlerStatus&x=Pkg.Event&x=Pkg.Issue&x=Pkg.Event.Kind&x=FileExt&x=App.NodePool&x=CloudCluster&x=CloudCluster%3CServer%3E&x=AppFields&x=Config&x=Nameable&x=DefaultInstance&x=ImplLanguageProtocol&x=Boxed%3C%5Bany%5D%3E&noSourceMapPointer=false' \
  -H 'Accept: text/javascript' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: undefined' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: c3env=lefv202310092005; c3app=gurusearchui; c3AppUrlPrefix=lefv202310092005/gurusearchui; c3csrf=SFMyNTYmZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SmhkV1FpT2lKak15NWhhU0lzSW1OeWRDSTZNVFk1T1RrMk1UTXdNREF3TUN3aWFYTnpJam9pWXpNdVlXa2lMQ0poZEhSeUlqb2llMXdpWlhod1hDSTZNakF4TlRVNE1EVXdNREF3TUN4Y0ltbGtYQ0k2WENKbVl6Z3dOREV6WWpFNU5qVmlNREZoWWpNeFpqRXpNVE15WVdNeE9UWXlPR1EyTkRBM05HRTJOVEkyTkRKbE1tTTRaREJpTVRnd1lUVTFabU5sWXpsbVhDSXNYQ0poY0hCY0lqcGNJbWRyWlhZNFpHVjJMV3hsWm5ZeU1ESXpNVEF3T1RJd01EVXRaM1Z5ZFhObFlYSmphSFZwWENJc1hDSnphV1JjSWpveGZTSXNJbVY0Y0NJNk1qQXhOVFU0TURVd01EQXdNQ3dpZEd0cGJtUWlPaUpEYzNKbVZHOXJaVzRpZlEueUc1RWQxN2ROdlhITFdYNndzNnBmbGczbFphR0FYcXdRS0hKakFKNHUxSQ%3D%3D; c3auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhcHAiOiJna2V2OGRldi1sZWZ2MjAyMzEwMDkyMDA1LWd1cnVzZWFyY2h1aSIsImlzcyI6ImMzLmFpIiwiZ3JvdXBzIjpbIkMzLkFwcEFkbWluIiwiQzMuRW52QWRtaW4iXSwic2lkIjoxLCJhdWQiOiJjMy5haSIsImlkcCI6IiIsImMzZ3JvdXBzIjpbIkMzLkFwcEFkbWluIiwiQzMuRW52QWRtaW4iXSwiaWRwZ3JvdXBzIjoie1wiT2lkY0lkcENvbmZpZzo6Z2tldjhkZXYuYzNkZXYuY2xvdWRcIjpbXCJkZXYuT2lkY0RlZmF1bHRHcm91cFwiXX0iLCJzc2lkeCI6IiIsIm5hbWUiOiJmYzgwNDEzYjE5NjViMDFhYjMxZjEzMTMyYWMxOTYyOGQ2NDA3NGE2NTI2NDJlMmM4ZDBiMTgwYTU1ZmNlYzlmIiwiaWQiOiJmYzgwNDEzYjE5NjViMDFhYjMxZjEzMTMyYWMxOTYyOGQ2NDA3NGE2NTI2NDJlMmM4ZDBiMTgwYTU1ZmNlYzlmIiwiZXhwIjoxNzAwMDQ3NzAwMDAwLCJlbWFpbCI6Imx1aXMuZmVybmFuZGV6LWRlLWxhLXZhcmFAYzMuYWkifQ.JVzQ5cZPsxr6WGxXf2xjJLYPIJq0Bmvgk3FfWQK9Y-hnuf-gKBZKsAbLb3a_Eu7JDtcoqlmXwzxIMp0QIhj7te4SW5k7XjCL-iGriouqP48isa30UbLplt95QwkLebvQlvcE4YclWslUydJtX7IfiW8r7CAvWMF_JpobwBgMDKMH8Ril8qYH3W60w9fusKr6QrWODcuxqFWiv3heNRVQbric-PLdZd1X7rdokxugOSCQinsCzvEiceoRowJ0PWJEJZVaHJ62VJs3qA6f7oU48FOElT_NOqd7G67f65vZtEZZd9IHumUCMWkGsdAv4-i1X37fbEMXgdXBi6E1XHjr6Q; c3auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhcHAiOiJna2V2OGRldi1sZWZ2MjAyMzEwMDkyMDA1LWMzIiwiaXNzIjoiYzMuYWkiLCJncm91cHMiOlsiQzMuRW52QWRtaW4iXSwic2lkIjoxLCJhdWQiOiJjMy5haSIsImlkcCI6IiIsImMzZ3JvdXBzIjpbIkMzLkVudkFkbWluIl0sImlkcGdyb3VwcyI6IntcIk9pZGNJZHBDb25maWc6OmdrZXY4ZGV2LmMzZGV2LmNsb3VkXCI6W1wiZGV2Lk9pZGNEZWZhdWx0R3JvdXBcIl19Iiwic3NpZHgiOiIiLCJuYW1lIjoiZmM4MDQxM2IxOTY1YjAxYWIzMWYxMzEzMmFjMTk2MjhkNjQwNzRhNjUyNjQyZTJjOGQwYjE4MGE1NWZjZWM5ZiIsImlkIjoiZmM4MDQxM2IxOTY1YjAxYWIzMWYxMzEzMmFjMTk2MjhkNjQwNzRhNjUyNjQyZTJjOGQwYjE4MGE1NWZjZWM5ZiIsImV4cCI6MTY5OTk3NzExMzAwMCwiZW1haWwiOiJsdWlzLmZlcm5hbmRlei1kZS1sYS12YXJhQGMzLmFpIn0.p5ENcNewKGQjGr83LXPkJadoNzUzl5-ajd2ZqSPBFF8QeHVO4S8vNIsGIeAm1tCD7S_0y2RxlEpzSwYv9Ppb37Wqvg-0HkScibODwbiZzXbtpPZnywT9inyO1BRQjPgtq-qlAAiPoQCkW-klMJDzOcCNQGL04Zco2Haz0xNnqtoWIYEJr3qX_4mwt_san8f-X5xKR33TWqtxrX73bj9AYaLMwA_KXc78e-rZh5OFbBxGJ2raXp8iQcyjCYMcusgXNDRkL_cmsX0wBwNtIf5ZQ-cuvQwUX4JgFvyFUDUZ5SG3JBiBXSwXEKoVY3TY_J9ift8Jm_J1dOJ7EOpRK79AnA; c3AppUrlPrefix=lefv202310092005/gurusearchui' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:50864/lefv202310092005/gurusearchui/static/console/index.html' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'X-C3-Language: en-US' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
}