#
# C3 Server web service specification
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.c3Cluster.service.web.name }}
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.c3Cluster.service.web.annotations }}
  #
  # Cloud provider-specific annotations, usually specified in the installation configuration file and aimed
  # at controlling the cloud provider ingress load balancer type and behavior.
  #
  annotations:
  {{- range $key, $value := .Values.c3Cluster.service.web.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end}}
  {{- end}}
spec:
  type: {{ .Values.c3Cluster.service.web.type }}
  selector:
    app: 'c3-app'
  ports:
    {{- if .Values.c3Cluster.service.web.ports }}
    {{- range $port := .Values.c3Cluster.service.web.ports }}
    - {{ toYaml $port | nindent 6 }}

    {{- end }}
    {{- end }}
