npm run start --prefix $C3_SERVER_ROOT/tools/bundler -- -e $URL -W /tmp/UI -a $C3_SERVER_ROOT/platform/repo -T $TOKEN -t studio:studio --logDir /tmp/UI/logs --bundler-max-mem 13000 --watcher --bundler --emit-to-server

URL=""
npm run start -- -e $URL -W /tmp/UI -a $C3_SERVER_ROOT/platform/repo -T $TOKEN -t studio:studio --logDir /tmp/UI/logs --bundler-max-mem 13000 --watcher --bundler --emit-to-server

TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhcHAiOiJna2V2OGRldi1sZWZ2MjAyMzExMTctZ3VydXNlYXJjaHVpIiwiaXNzIjoiYzMuYWkiLCJncm91cHMiOlsiQzMuQXBwQWRtaW4iLCJDMy5FbnZBZG1pbiJdLCJzaWQiOjEsImF1ZCI6ImMzLmFpIiwiaWRwIjoiIiwiYzNncm91cHMiOlsiQzMuQXBwQWRtaW4iLCJDMy5FbnZBZG1pbiJdLCJpZHBncm91cHMiOiJ7XCJPaWRjSWRwQ29uZmlnOjpna2V2OGRldi5jM2Rldi5jbG91ZFwiOltcImRldi5PaWRjRGVmYXVsdEdyb3VwXCJdfSIsInNzaWR4IjoiIiwibmFtZSI6ImZjODA0MTNiMTk2NWIwMWFiMzFmMTMxMzJhYzE5NjI4ZDY0MDc0YTY1MjY0MmUyYzhkMGIxODBhNTVmY2VjOWYiLCJhY3Rpb25pZCI6Ijg5MDQuMTk0MDk5MTE5IiwiaWQiOiJmYzgwNDEzYjE5NjViMDFhYjMxZjEzMTMyYWMxOTYyOGQ2NDA3NGE2NTI2NDJlMmM4ZDBiMTgwYTU1ZmNlYzlmIiwiZXhwIjoxNzAxMjMxOTI3MDAwLCJlbWFpbCI6Imx1aXMuZmVybmFuZGV6LWRlLWxhLXZhcmFAYzMuYWkifQ.OnIQdpq53lKyPH23WRWJ7H9CTwkdzqWVmb58J85AN19TQnrAM8hswutQpgmhm6sk-F8yo3-LzTRlIa1NqlVWaluNqms2Ch5yISVWqtmvGNz5zM245jf4Pvvkrnh5k_enfkrakpzLAZDlRUBXpdCXpHBhv1quMOnDSrMjTHLiJYINZjRVf694zK8V6oFGPednc9UOJnGAeQEVU0RgDX5B43lhCH7ChaFt0v984QFXm00UUx4EDMkbDQ6suLfZeTD1NJypLSkFxo4vRxa8yKPwhCnP0GCdnyQ8XsfOWeznF8z4hTQUjiHifR0JBR9ELPSLWlbMPKSzIW7S3tR9Q2CaTQ

npm run start -- -e https://gkev8dev.c3dev.cloud/lefv20231117/gurusearchui/ --setup --watcher --bundler -t prov:gurusearch --logDir /Users/lefv/c3/logs/gurusearchui/release3 -W /Users/lefv/c3/UI/gurusearchui/release3 --out-dir /Users/lefv/c3/output_dir/gurusearchui/release3 -a /Users/lefv/test/20231115/prov -auth-token $TOKEN


npm run start -- --setup --watcher --bundler -W /Users/lefv/c3/UI/gurusearchui/release3 -e https://gkev8dev.c3dev.cloud/lefv20231117/gurusearchui/ --auth-token $TOKEN -t prov:gurusearchui --out-dir /Users/lefv/c3/output_dir/gurusearchui/release3 -a /Users/lefv/test/20231115/prov --emit-to-server --logDir /Users/lefv/c3/logs/gurusearchui/release3 -v