export const CONFIG = {
  // Path to root repo. Exclude trailing slash
  PATH_TO_PACKAGE_REPO: '/Users/lefv/c3/c3fed-guru/cornea/',

  // Listen to file updates within these packages
  PACKAGES_TO_SYNC: ['guruSearch', 'guruSearchUI'],

  // Exclude trailing slash
  APPURL: 'https://gkev8genai.c3-e.com/c3fedguru/gurusearchui',

  // Basic auth token for BA:BA
  // AUTH_TOKEN: 'Basic QkE6QkE=',
  AUTH_TOKEN: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhcHAiOiJna2V2OGdlbmFpLWMzZmVkZ3VydS1ndXJ1c2VhcmNodWkiLCJpc3MiOiJjMy5haSIsImdyb3VwcyI6WyJDMy5BcHBBZG1pbiIsIkMzLkVudkFkbWluIl0sInNpZCI6MSwiYXVkIjoiYzMuYWkiLCJpZHAiOiIiLCJjM2dyb3VwcyI6WyJDMy5BcHBBZG1pbiIsIkMzLkVudkFkbWluIl0sImlkcGdyb3VwcyI6IntcIk9pZGNJZHBDb25maWc6OmdrZXY4Z2VuYWkuYzMtZS5jb21cIjpbXCJna2V2OGMzZ2VuYWkuYzMtZS5jb20vU3R1ZGlvVXNlclwiXX0iLCJzc2lkeCI6IiIsIm5hbWUiOiIzMWNmNGZlZThjYWExYTZlMzAxYmQ3OTNkNTUzODUzYmM2NzYxM2RkY2Q5MjJiNWNkNTg1NzIwZDMyN2U2ZjEzIiwiYWN0aW9uaWQiOiI5NjE4LjI0OTQyMjMyIiwiaWQiOiIzMWNmNGZlZThjYWExYTZlMzAxYmQ3OTNkNTUzODUzYmM2NzYxM2RkY2Q5MjJiNWNkNTg1NzIwZDMyN2U2ZjEzIiwiZXhwIjoxNzA3OTQwMjU3MDAwLCJlbWFpbCI6Imx1aXMuZmVybmFuZGV6LWRlLWxhLXZhcmFAYzMuYWkifQ.u4B4KqMtZXsLFpsmofiX5FsXu0hSgiS8RyHa0yXffyT0VtTomvQqQxLqgUfuLVnxVfhCLZIESLLs55quWfl_RR29EQl5J8cZ7tH2gatdAJVe6vniOlztdrOfLXIlgdUSBzqaAY_oaDALFn_6P80eNxthT0pvXQu6dLB2UUpGR2NRheISCBQyw25PY-0lLaUt9FQU20glfGuh1UVjIEFMEje5g2u_V7YjCIN93YWwwpuOXxWvLxmTkAucqe0Mnk1EzGODHLLBcGzVeGRwRNLGFmXZKMN8Qsh6msyNMSZ5nc3zU28cC2gW2qqSEN4x9lHtr1NzIZ8NIohpi_2qJrFU3w'
};
