apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-selenium-chrome'
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      function: 'selenium-chrome'
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        function: 'selenium-chrome'
    spec:
      containers:
      - image: '{{ .Values.c3Selenium.chrome.image }}:{{ coalesce .Values.c3Selenium.chrome.tag .Chart.AppVersion }}'
        imagePullPolicy: IfNotPresent
        name: selenium-chrome
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 4444
          protocol: TCP
        - containerPort: 5900
          protocol: TCP
        volumeMounts:
          - name: 'shared-memory'
            mountPath: '/dev/shm'
          {{- if .Values.c3ServerRoot }}
          - name: 'sources'
            mountPath: '/src'
            readOnly: true
          {{- end }}
          {{- if .Values.c3Selenium.sharedFileSystem.mountPath }}
          - name: 'c3-cluster-shared'
            mountPath: '{{ .Values.c3Selenium.sharedFileSystem.mountPath  }}'
            subPath: '{{ .Values.c3Selenium.sharedFileSystem.subPath }}'
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 120
      volumes:
        - name: 'shared-memory'
          emptyDir:
            medium: 'Memory'
        {{- if .Values.c3ServerRoot }}
        - name: 'sources'
          hostPath:
            path: '{{ .Values.c3ServerRoot }}'
        {{- end }}
        {{- if .Values.c3Selenium.sharedFileSystem.local }}
        - name: 'c3-cluster-shared'
          hostPath:
            path: '{{ .Values.c3Selenium.sharedFileSystem.local }}'
        {{- end }}
