export declare const getPkgId: () => string;
export declare const setPkgId: (value: string) => void;
export declare const getPrivateKey: () => string;
export declare const setPrivateKey: (value: string) => void;
export declare const getC3Key: () => string;
export declare const setC3Key: (value: string) => void;
export declare const getC3: () => void;
export declare const setC3: (value: any) => void;
export declare const get: () => void;
export declare const set: (value: any) => void;
export declare const inst: (value: any) => void;
export declare const kill: (value: any) => void;
type C3 = {
    id?: number;
    name?: string;
    c3Key?: string;
    pkgId?: string;
    get?: any;
    set?: any;
};
export declare const c3: C3;
export {};
