# Default values for a C3 Cluster chart.
# This is a YAML-formatted file.

c3Local:

  namespace: default
  
  #
  # We use busyboxy to run init containers that check on the state of dependencies and wait until the
  # dependency services are available. We found that some busybox releases are broken with respect to how
  # nslookup works. 1.28 works well.
  #
  busybox:
    registry: 'ci-artifacts.c3.ai'
    repository: 'busybox'
    tag: '1.28'

#
# Note: configuration values for persistence components are declared in the values.yaml file that is packages with
# the c3-persistence chart. They can be overridden here but that is normally not necessary.
#
c3-persistence:
  postgresql:
    enabled: true
    #
    # postgresql OPS chart configuration
    #
    service:
      annotations:
        metallb.universe.tf/address-pool: test
      type: LoadBalancer

  #
  # Enable Vault for local charts.
  #
  vault:
    enabled: false
    server:
      service:
        type: LoadBalancer
  #
  # cassandra OPS chart configuration
  #
  cassandra:
    enabled: true
    replicaCount: 1
    service:
      annotations:
        metallb.universe.tf/address-pool: test
      type: LoadBalancer
    extraEnvVars:
      - name: JVM_EXTRA_OPTS
        value: '-Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=0.0.0.0'
      - name: LOCAL_JMX
        value: 'no'
      - name: MAX_HEAP_SIZE
        value: '2048m'
      - name: HEAP_NEWSIZE
        value: '700m'
