#!/bin/bash

function startExMachina() {
  mkdir -p ~/c3exmachina/
  VAD_FIXED_AUTH=true $JAVA_HOME/bin/java -jar $(npm root -g)/c3-exmachina/c3-vad*.jar > ~/c3exmachina/exmachina.log 2>&1 &
}

function start() {
  s=$(status)
  if [ "$s" -eq 1 ]; then
    echo "C3 AI Ex Machina is already running! Please use stop or restart."
  else
    #Hive dependencies currently not working for npm package
    if [ -z "$ENABLE_HIVE" ]; then
      echo "Disabling Hive Server. To enable, user '--enableHive true' and re-start C3 AI Ex Machina."
      ENABLE_HIVE=false
    fi
    if [ -n "$TENANT" ] && [ -n "$TAG" ]; then
      echo "Starting C3 AI Ex Machina for Tenant "$TENANT" Tag "$TAG
      VAD_C3_TENANT=$TENANT VAD_C3_TAG=$TAG VAD_START_HIVE_SERVER=$ENABLE_HIVE startExMachina
    else
      echo "Starting C3 AI Ex Machina"
      VAD_START_HIVE_SERVER=$ENABLE_HIVE startExMachina
    fi
  fi
}

function stop() {
  if [ "$(status)" == "0" ]
  then
    echo "C3 AI Ex Machina is not running."
  else
    PID=$(/bin/ps -e -O pid,cmd | grep c3-vad | grep -v grep | awk '{print $1}')
    echo "Stopping C3 AI Ex Machina (PID "$PID")"
    kill -9 $PID
  fi
}

function status() {
  if /bin/ps -e -O pid,cmd | grep c3-vad | grep c3-vad | grep -vq grep
  then
      echo "1"
  else
      echo "0"
  fi
}

function logs() {
  less -n +F ~/c3exmachina/exmachina.log
}

function restart() {
  stop
  start
}

function usage() {
  echo ""
  echo "Usage:"
  echo "    c3-exmachina start            # start C3 AI Ex Machina server"
  echo "    c3-exmachina stop             # stop C3 AI Ex Machina server"
  echo "    c3-exmachina status           # check C3 AI Ex Machina process status"
  echo "    c3-exmachina logs             # show C3 AI Ex Machina logs"
  echo "    c3-exmachina restart          # restart C3 AI Ex Machina"
  echo "    c3-exmachina usage            # help menu"

  echo ""
  echo "Options:"
  echo "    -t | --tenant tenant          # select tenant to run C3 AI Ex Machina with. default dev"
  echo "    -g | --tag tag                # select tag to run C3 AI Ex Machina with. default spark"
  echo "    -h | --enableHive tag         # whether to start hive server. default false"
  echo "You should set tenant and tag only if you are accessing C3 AI Ex Machina UI without C3 Tools."
  echo "Tenant and tag settings do not apply to In Memory Analytics Server."
}

USAGE=$1

# Processing command line options
while [[ $# -gt 1 ]]
do
key="$1"

case $key in
    -t|--tenant)
    TENANT="$2"
    shift;;
    -g|--tag)
    TAG="$2"
    shift;;
    -h|--enableHive)
    ENABLE_HIVE="$2"
    shift;;
    *)
    # Unknown option
    ;;
esac
shift
done

case $USAGE in
  start)           start         ;;
  stop)            stop          ;;
  status)          status        ;;
  logs)            logs          ;;
  restart)         restart       ;;

  *)               usage         ;;
esac
