c3-persistence:
  cassandra:
    env:
      JVM_OPTS: '-Djava.rmi.server.hostname=localhost'
      CASSANDRA_LISTEN_ADDRESS: 127.0.0.1
      CASSANDRA_BROADCAST_ADDRESS: $(POD_IP)

zookeeper:
  listenOnAllIPs: true

c3Cluster:
  istio:
    enabled: true
