#
# These configuration values will be applied to persistence components deployed by this chart, when this chart is
# declared as a dependency for other top-level charts (c3-cluster, c3-builder). These values can be overridden
# from dependent chart's values.yaml, but that is normally not necessary.
#
c3Persistence:
  secrets:
    registryc3ai:
      #
      # Set "c3Persistence.secrets.registryc3ai.dockerconfigjson" as an external value to trigger the
      # corresponding secret deployment. Prefix with "c3-persistence." if part of a c3-cluster deployment.
      #
      dockerconfigjson:
    ciregistryc3iotio:
      #
      # Set "c3Persistence.secrets.ciregistryc3iotio.dockerconfigjson" as an external value to trigger the
      # corresponding secret deployment. Prefix with "c3-persistence." if part of a c3-cluster deployment.
      #
      dockerconfigjson:

#
# HashiCorp Vault settings:
#
# We use Developer mode: auto initializes and unseals the vault; uses in memory storage rather than disk (PV).
#
# Set vault.enabled to true to enable Vault.
#
vault:
  server:
    extraArgs: "-dev-plugin-dir=/vault/file/"
    dev:
      enabled: true
    image:
      repository: ci-artifacts.c3.ai/hashicorp/vault
      tag: '1.4.0'
  injector:
    enabled: false
postgresql:
  # TODO PLAT-25496 This initializes PostgreSQL admin user password. The value is hardcoded in the C3 code.
  postgresqlPassword: 'c3postgres'
  initdbScripts:
    create-super-user.sql: |
      CREATE ROLE pgadminusername LOGIN SUPERUSER PASSWORD 'pgadminpassword';

  #
  # postgresql OPS chart configuration
  #
  #image:
  #  registry: registry.c3.ai
  #  repository: postgres
  #  tag: "9.6.20.1"
  #  pullSecrets:
  #    name: registryc3ai
  #
  # postgresql OPS chart which is moved to ci-artifacts.c3.ai, to avoid the authentication
  #
  image:
    registry: ci-artifacts.c3.ai
    repository: postgres
    tag: "9.6.20.1"
    pullPolicy: IfNotPresent

  #
  # postgresql OPS chart OpenShift configuration
  #
#  securityContext:
#    fsGroup: 1000600000
#    runAsUser: 1000600001
#    runAsGroup: 1000600001
#  containerSecurityContext:
#    readOnlyRootFilesystem: true
#    allowPrivilegeEscalation: false
#    runAsUser: 1000600001
cassandra:
  replicaCount: 1
  #image:
  #  registry: registry.c3.ai
  #  repository: cassandra
  #  tag: "3.11.9.2"
  #  pullSecrets:
  #    name: registryc3ai

  # cassandra OPS chart which is moved to ci-artifacts.c3.ai, to avoid the authentication
  #
  image:
    registry: ci-artifacts.c3.ai
    repository: cassandra
    tag: "3.11.9.2"
    pullPolicy: IfNotPresent

  securityContext:
    runAsUser: 503
    #runAsUser: 1000600001
    runAsGroup: 20
    #runAsGroup: 1000600001
    #fsGroup: 1000600000
  containerSecurityContext:
    runAsUser: 503
    #runAsUser: 1000600001
    #readOnlyRootFilesystem: true
    #allowPrivilegeEscalation: false
  extraEnvVars:
    - name: JVM_EXTRA_OPTS
      value: '-Dcom.sun.management.jmxremote.authenticate=false'
    - name: LOCAL_JMX
      value: 'no'
    - name: MAX_HEAP_SIZE
      value: '2048m'
    - name: HEAP_NEWSIZE
      value: '700m'
  resources:
    requests:
      cpu: 250m
