/**
 * Configuration keys and environment variables
 *
 * All environment variable names, configuration keys, and default values.
 */

export const ENV_VARS = {
  // Core environment
  NODE_ENV: 'NODE_ENV',
  USER: 'USER',
  HOSTNAME: 'HOSTNAME',
  HOME: 'HOME',
  SHELL: 'SHELL',
  EDITOR: 'EDITOR',
  VISUAL: 'VISUAL',

  // Platform-specific
  USERPROFILE: 'USERPROFILE',
  APPDATA: 'APPDATA',
  LOCALAPPDATA: 'LOCALAPPDATA',
  COMSPEC: 'COMSPEC',

  // LSH API configuration
  LSH_API_ENABLED: 'LSH_API_ENABLED',
  LSH_API_PORT: 'LSH_API_PORT',
  LSH_API_KEY: 'LSH_API_KEY',
  LSH_JWT_SECRET: 'LSH_JWT_SECRET',
  LSH_ALLOW_DANGEROUS_COMMANDS: 'LSH_ALLOW_DANGEROUS_COMMANDS',

  // LSH SaaS API
  LSH_SAAS_API_PORT: 'LSH_SAAS_API_PORT',
  LSH_SAAS_API_HOST: 'LSH_SAAS_API_HOST',
  LSH_CORS_ORIGINS: 'LSH_CORS_ORIGINS',

  // Secrets management
  LSH_SECRETS_KEY: 'LSH_SECRETS_KEY',
  LSH_MASTER_KEY: 'LSH_MASTER_KEY',

  // Feature flags
  LSH_LOCAL_STORAGE_QUIET: 'LSH_LOCAL_STORAGE_QUIET',
  LSH_V1_COMPAT: 'LSH_V1_COMPAT',
  LSH_STORACHA_ENABLED: 'LSH_STORACHA_ENABLED',
  DISABLE_IPFS_SYNC: 'DISABLE_IPFS_SYNC',

  // Logging
  LSH_LOG_LEVEL: 'LSH_LOG_LEVEL',
  LSH_LOG_FORMAT: 'LSH_LOG_FORMAT',
  NO_COLOR: 'NO_COLOR',

  // Webhooks
  LSH_ENABLE_WEBHOOKS: 'LSH_ENABLE_WEBHOOKS',
  WEBHOOK_PORT: 'WEBHOOK_PORT',
  GITHUB_WEBHOOK_SECRET: 'GITHUB_WEBHOOK_SECRET',
  GITLAB_WEBHOOK_SECRET: 'GITLAB_WEBHOOK_SECRET',
  JENKINS_WEBHOOK_SECRET: 'JENKINS_WEBHOOK_SECRET',

  // Database and persistence
  DATABASE_URL: 'DATABASE_URL',
  SUPABASE_URL: 'SUPABASE_URL',
  SUPABASE_ANON_KEY: 'SUPABASE_ANON_KEY',
  REDIS_URL: 'REDIS_URL',

  // Monitoring
  MONITORING_API_PORT: 'MONITORING_API_PORT',

  // Stripe billing
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',
  STRIPE_PRICE_PRO_MONTHLY: 'STRIPE_PRICE_PRO_MONTHLY',
  STRIPE_PRICE_PRO_YEARLY: 'STRIPE_PRICE_PRO_YEARLY',
  STRIPE_PRICE_ENTERPRISE_MONTHLY: 'STRIPE_PRICE_ENTERPRISE_MONTHLY',
  STRIPE_PRICE_ENTERPRISE_YEARLY: 'STRIPE_PRICE_ENTERPRISE_YEARLY',

  // Email (Resend)
  RESEND_API_KEY: 'RESEND_API_KEY',
  EMAIL_FROM: 'EMAIL_FROM',
  BASE_URL: 'BASE_URL',
} as const;

export const DEFAULTS = {
  // Version
  VERSION: '0.5.1',

  // Ports
  API_PORT: 3030,
  SAAS_API_PORT: 3031,
  WEBHOOK_PORT: 3033,
  MONITORING_API_PORT: 3031,
  MONITORING_PORT: 3000,

  // Hosts
  DEFAULT_HOST: '0.0.0.0',
  DEFAULT_CORS_ORIGINS: ['*'],

  // URLs
  REDIS_URL: 'redis://localhost:6379',
  DATABASE_URL: 'postgresql://localhost:5432/cicd',
  STRIPE_API_URL: 'https://api.stripe.com/v1',
  RESEND_API_URL: 'https://api.resend.com/emails',
  LSH_APP_URL: 'https://app.lsh.dev',
  LSH_DOCS_URL: 'https://docs.lsh.dev',
  KUBO_RELEASES_URL: 'https://api.github.com/repos/ipfs/kubo/releases/latest',

  // Email defaults
  DEFAULT_EMAIL_FROM: 'noreply@lsh.dev',

  // Timeouts and intervals (in milliseconds)
  CHECK_INTERVAL_MS: 2000,
  REQUEST_TIMEOUT_MS: 10000,
  DAEMON_RESTART_DELAY_MS: 1000,
  JOB_TIMEOUT_1H_MS: 3600000,
  JOB_TIMEOUT_5M_MS: 300000,
  JOB_TIMEOUT_1M_MS: 60000,
  JOB_TIMEOUT_2H_MS: 7200000,

  // Sizes
  MAX_BUFFER_SIZE_BYTES: 1024 * 1024, // 1MB
  MAX_LOG_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
  MAX_COMMAND_LENGTH: 10000,
  SOCKET_BUFFER_SIZE: 1024,
  MAX_EVENTS_LIMIT: 100,

  // History limits
  MAX_HISTORY_SIZE: 10000,
  HISTORY_SAVE_INTERVAL_MS: 30000,

  // Limits
  MAX_COMMAND_CHAINS: 5,
  MAX_PIPE_USAGE: 3,

  // Cache and retention
  REDIS_CACHE_EXPIRY_SECONDS: 3600, // 1 hour
  METRICS_RETENTION_SECONDS: 30 * 24 * 60 * 60, // 30 days

  // Shell defaults
  DEFAULT_SHELL_UNIX: '/bin/sh',
  DEFAULT_SHELL_WIN: 'cmd.exe',
  DEFAULT_EDITOR: 'vi',
} as const;
