[tool.poetry]
name = "lpy"
version = "0.1.0"
description = ""
authors = ["lefv <luis.fernandez-de-la-vara@c3.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
requests = "^2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lpy = "lpy.lpy:main"