/**
 * Secrets Management Commands
 * Sync .env files across development environments
 */

import { Command } from 'commander';
import SecretsManager from '../../lib/secrets-manager.js';
import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

export async function init_secrets(program: Command) {
  const secretsCmd = program
    .command('secrets')
    .description('Manage environment secrets across machines');

  // Push secrets to cloud
  secretsCmd
    .command('push')
    .description('Push local .env to encrypted cloud storage')
    .option('-f, --file <path>', 'Path to .env file', '.env')
    .option('-e, --env <name>', 'Environment name (dev/staging/prod)', 'dev')
    .action(async (options) => {
      try {
        const manager = new SecretsManager();
        await manager.push(options.file, options.env);
      } catch (error: any) {
        console.error('❌ Failed to push secrets:', error.message);
        process.exit(1);
      }
    });

  // Pull secrets from cloud
  secretsCmd
    .command('pull')
    .description('Pull .env from encrypted cloud storage')
    .option('-f, --file <path>', 'Path to .env file', '.env')
    .option('-e, --env <name>', 'Environment name (dev/staging/prod)', 'dev')
    .option('--force', 'Overwrite without creating backup')
    .action(async (options) => {
      try {
        const manager = new SecretsManager();
        await manager.pull(options.file, options.env, options.force);
      } catch (error: any) {
        console.error('❌ Failed to pull secrets:', error.message);
        process.exit(1);
      }
    });

  // List environments
  secretsCmd
    .command('list [environment]')
    .alias('ls')
    .description('List all stored environments or show secrets for specific environment')
    .action(async (environment) => {
      try {
        const manager = new SecretsManager();

        // If environment specified, show secrets for that environment
        if (environment) {
          await manager.show(environment);
          return;
        }

        // Otherwise, list all environments
        const envs = await manager.listEnvironments();

        if (envs.length === 0) {
          console.log('No environments found. Push your first .env with: lsh secrets push');
          return;
        }

        console.log('\n📦 Available environments:\n');
        for (const env of envs) {
          console.log(`  • ${env}`);
        }
        console.log();
      } catch (error: any) {
        console.error('❌ Failed to list environments:', error.message);
        process.exit(1);
      }
    });

  // Show secrets (masked)
  secretsCmd
    .command('show')
    .description('Show secrets for an environment (masked)')
    .option('-e, --env <name>', 'Environment name', 'dev')
    .action(async (options) => {
      try {
        const manager = new SecretsManager();
        await manager.show(options.env);
      } catch (error: any) {
        console.error('❌ Failed to show secrets:', error.message);
        process.exit(1);
      }
    });

  // Generate encryption key
  secretsCmd
    .command('key')
    .description('Generate a new encryption key')
    .action(async () => {
      const { randomBytes } = await import('crypto');
      const key = randomBytes(32).toString('hex');
      console.log('\n🔑 New encryption key (add to your .env):\n');
      console.log(`LSH_SECRETS_KEY=${key}\n`);
      console.log('💡 Tip: Share this key securely with your team to sync secrets.');
      console.log('    Never commit it to git!\n');
    });

  // Create .env file
  secretsCmd
    .command('create')
    .description('Create a new .env file')
    .option('-f, --file <path>', 'Path to .env file', '.env')
    .option('-t, --template', 'Create with common template variables')
    .action(async (options) => {
      try {
        const envPath = path.resolve(options.file);

        // Check if file already exists
        if (fs.existsSync(envPath)) {
          console.log(`❌ File already exists: ${envPath}`);
          console.log('💡 Use a different path or delete the existing file first.');
          process.exit(1);
        }

        // Create template content if requested
        let content = '';
        if (options.template) {
          content = `# Environment Configuration
# Generated by LSH Secrets Manager

# Application
NODE_ENV=development
PORT=3000

# Database
DATABASE_URL=

# API Keys
API_KEY=

# LSH Secrets (for cross-machine sync)
# LSH_SECRETS_KEY=

# Add your environment variables below
`;
        }

        // Create the file
        fs.writeFileSync(envPath, content, 'utf8');

        console.log(`✅ Created .env file: ${envPath}`);
        if (options.template) {
          console.log('📝 Template variables added - update with your values');
        }
        console.log('');
        console.log('Next steps:');
        console.log(`  1. Edit the file: ${options.file}`);
        console.log(`  2. Push to cloud: lsh lib secrets push -f ${options.file}`);
        console.log('');
      } catch (error: any) {
        console.error('❌ Failed to create .env file:', error.message);
        process.exit(1);
      }
    });

  // Delete .env file with confirmation
  secretsCmd
    .command('delete')
    .description('Delete .env file (requires confirmation)')
    .option('-f, --file <path>', 'Path to .env file', '.env')
    .option('-y, --yes', 'Skip confirmation prompt')
    .action(async (options) => {
      try {
        const envPath = path.resolve(options.file);

        // Check if file exists
        if (!fs.existsSync(envPath)) {
          console.log(`❌ File not found: ${envPath}`);
          process.exit(1);
        }

        console.log('⚠️  WARNING: You are about to delete a .env file!');
        console.log('');
        console.log(`File: ${envPath}`);
        console.log('');

        // Skip confirmation if --yes flag is provided
        if (!options.yes) {
          console.log('To confirm deletion, please type the full path of the file:');
          console.log(`Expected: ${envPath}`);
          console.log('');

          const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout,
          });

          const answer = await new Promise<string>((resolve) => {
            rl.question('Enter path to confirm: ', (ans) => {
              rl.close();
              resolve(ans.trim());
            });
          });

          if (answer !== envPath) {
            console.log('');
            console.log('❌ Confirmation failed - path does not match');
            console.log('Deletion cancelled');
            process.exit(1);
          }
        }

        // Delete the file
        fs.unlinkSync(envPath);

        console.log('');
        console.log(`✅ Deleted: ${envPath}`);
        console.log('');
        console.log('💡 Tip: You can still pull from cloud if you pushed previously:');
        console.log(`   lsh lib secrets pull -f ${options.file}`);
        console.log('');
      } catch (error: any) {
        console.error('❌ Failed to delete .env file:', error.message);
        process.exit(1);
      }
    });
}

export default init_secrets;
