apiVersion: v1
kind: ConfigMap
metadata:
  name: 'boot-config-c3-server'
data:
  config.json: |
    {
       "type": "BootConfig",
       {{- if $.Values.c3.configFramework.bootConfig.enabled }}
       "config": {
         "root": "{{ $.Values.c3.configFramework.bootConfig.credentials.configRoot }}",
         "accessKey": "{{ $.Values.c3.configFramework.bootConfig.credentials.accessKey }}",
         {{- if $.Values.c3.configFramework.bootConfig.credentials.useNodeCloudIdentity }}
         "useNodeCloudIdentity": "{{ $.Values.c3.configFramework.bootConfig.credentials.useNodeCloudIdentity }}",
         "cloudIdentity": "{{ $.Values.c3.configFramework.bootConfig.credentials.cloudIdentity }}",
         {{- else }}
         "secretKey": "{{ $.Values.c3.configFramework.bootConfig.credentials.secretKey }}",
         {{- end }}
         "region": "{{ $.Values.c3.configFramework.bootConfig.credentials.region }}"
       },
       "vault": {
         "root": "{{ $.Values.c3.configFramework.bootConfig.credentials.vaultRoot }}",
         "accessKey": "{{ $.Values.c3.configFramework.bootConfig.credentials.accessKey }}",
         {{- if $.Values.c3.configFramework.bootConfig.credentials.useNodeCloudIdentity }}
         "useNodeCloudIdentity": "{{ $.Values.c3.configFramework.bootConfig.credentials.useNodeCloudIdentity }}",
         "cloudIdentity": "{{ $.Values.c3.configFramework.bootConfig.credentials.cloudIdentity }}",
         {{- else }}
         "secretKey": "{{ $.Values.c3.configFramework.bootConfig.credentials.secretKey }}",
         {{- end }}
         "region": "{{ $.Values.c3.configFramework.bootConfig.credentials.region }}"
       },
       "env": {
         "id": "{{ $.Values.c3.cluster.name }}-{{ $.Values.c3.cluster.environment.name }}",
         "name": "{{ $.Values.c3.cluster.environment.name }}",
         "label": "{{ $.Values.c3.cluster.environment.name }}",
         "configuredServerVersion": "{{ $.Values.c3.configFramework.bootConfig.clusterApp.configuredServerVersion }}",
         "configuredCloudNamespace": "{{ .Release.Namespace }}",
         "singleNode": "{{ $.Values.c3.cluster.environment.singleNode }}"
       },
       "app": {
         "id": "{{ $.Values.c3.cluster.name }}-{{ $.Values.c3.cluster.environment.name }}-c3",
         "rootPkg": "platform",
         "rootPkgVersion": "{{ $.Values.c3.configFramework.bootConfig.clusterApp.configuredServerVersion }}",
         "name": "c3",
         "label": "c3",
         "code": "1",
         "mode": "{{ $.Values.c3.configFramework.bootConfig.clusterApp.mode }}",
         "configuredServerVersion": "{{ $.Values.c3.configFramework.bootConfig.clusterApp.configuredServerVersion }}"
       }
      {{- end }}
    }
