apiVersion: v1
kind: ConfigMap
metadata:
  name: 'pre-stop'
data:
  pre-stop.sh: |
    #!/bin/bash
    set +e

    NOW=`date +"%Y-%m-%d_%H-%M-%S"`
    LOGFILE={{ .Values.c3.log.mountPath }}/c3-server.log

    {
      echo
      echo "PRESTOP FORENSICS"
      echo "Pod died at: ${NOW}"
      #echo == Open Connections =======
      #netstat -an
      echo

      echo == Process Status info ===================
      cat /proc/1/status
      echo

      pid=$(jps | grep BootstrapServer | awk '{print $1}')
      echo == JVM Memory usage ======================
      jcmd $pid VM.native_memory
      echo

      echo == Thread dump ===========================
      jcmd $pid Thread.print
    
      # Each cloud provider has an internal IPv4 address where it makes the metadata of a VM available.
      # This endpoint is different for each cloud-provider and is only accessible from within the VM.
      # For GCP it's http://metadata.google.internal/computeMetadata/v1/instance
      # For AWS it's http://169.254.169.254/latest/meta-data
      # For Azure it's http://169.254.169.254/metadata/instance
    
      echo == PREEMPTION DETAILS ===================
      if curl -s -f "http://metadata.google.internal/computeMetadata/v1/instance/id" -H "Metadata-Flavor: Google" > /dev/null; then
        echo "Pod is running on a GKE-VM"
        PREEMPTED=$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/preempted" -H "Metadata-Flavor: Google")
        echo "VM Preemption Event=$PREEMPTED"
      elif curl -s -f "http://169.254.169.254/latest/meta-data/"; then
        echo "Pod is running on an EKS-VM"
      elif curl -s -f -H "Metadata:true" --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01"; then
        echo "Pod is running on an AKS-VM"
      fi
      
    } >> $LOGFILE 2>&1
