export declare const getPkgId: () => string;
export declare const setPkgId: (value: string) => void;
export declare const getPrivateKey: () => string;
export declare const setPrivateKey: (value: string) => void;
export declare const getKey: () => string;
export declare const setKey: (value: string) => void;
export declare const getShell: () => void;
export declare const setShell: (value: any) => void;
export declare const setCmdMap: (key: string, value: any) => void;
export declare const getCmdMap: () => Map<any, any>;
export declare const get: (key: any) => any;
export declare const set: (key: any, value: any) => any;
export declare const inst: (value: any) => void;
export declare const kill: (value: any) => void;
type LSH = {
    key?: any;
    id?: number;
    name?: string;
    session?: string;
    pkgId?: string;
    get?: any;
    set?: any;
    commands?: any;
};
export declare const lsh: LSH;
export {};
