export declare const getPkgId: () => string;
export declare const setPkgId: (value: string) => void;
export declare const getPrivateKey: () => string;
export declare const setPrivateKey: (value: string) => void;
export declare const getKey: () => string;
export declare const setKey: (value: string) => void;
export declare const getShell: () => void;
export declare const setShell: (value: any) => void;
export declare const get: () => void;
export declare const set: (value: any) => void;
export declare const inst: (value: any) => void;
export declare const kill: (value: any) => void;
type LSH = {
    id?: number;
    name?: string;
    key?: string;
    session?: string;
    pkgId?: string;
    get?: any;
    set?: any;
};
export declare const lsh: LSH;
export {};
