version: '3.9'
services:
  reposilite:
    image: maven_repo_server:latest
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx${MEMORY} ${JAVA_COMPOSE_OPTS}
      - REPOSILITE_OPTS=--port ${PORT} ${REPOSILITE_COMPOSE_OPTS}
    # volumes:
    #   - /Users/lefv/docker/Dockerfiles/maven_repo_manager/data:/host/data
    restart: unless-stopped
    # stdin_open: true
    # tty: true
    # entrypoint: ./docker-entrypoint.sh    #   - /usr/local/lib/c3/java
    # entrypoint: /usr/bin/tail
    # command: "-f /dev/null"
  # cass:
  #   image: cassandra:3.11
  #   restart: unless-stopped
  #   mem_limit: 8g
  #   ports:
  #     - 9042:9042
  # pg:
  #   image: postgres:15
  #   restart: unless-stopped
  #   mem_limit: 4g
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: c3
  #     POSTGRES_PASSWORD: c3postgres
  #     POSTGRES_DB: c3
