#
# C3 Server bootstrap node configuration map
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: 'c3-cluster'
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:

  #
  # Cassandra
  #

  K8S_CASS_HOST_PREFIX: 'c3'
  K8S_CASS_KNOWN_HOSTS: {{ if .Values.c3Cluster.cassandra.knownNode -}}
    '{{ .Values.c3Cluster.cassandra.knownNode }}'
    {{- else -}}
      '{{ .Release.Name }}-cassandra-0.{{ .Release.Name }}-cassandra-headless.{{ .Release.Namespace }}'
    {{- end }}
  K8S_CASS_PORT: '9160'

  #
  # Zookeeper
  #

  K8S_ZK_SERVERS: {{ if .Values.c3Cluster.zookeeperClient.hosts -}}
    '{{ .Values.c3Cluster.zookeeperClient.hosts }}'
    {{- else if .Values.c3Cluster.zookeeperClient.enableTls -}}
    '{{ .Release.Name }}-zookeeper-0.{{ .Release.Name }}-zookeeper-headless.{{ .Release.Namespace }}:3181,{{ .Release.Name }}-zookeeper-1.{{ .Release.Name }}-zookeeper-headless.{{ .Release.Namespace }}:3181,{{ .Release.Name }}-zookeeper-2.{{ .Release.Name }}-zookeeper-headless.{{ .Release.Namespace }}:3181'
    {{- else -}}
    '{{ .Release.Name }}-zookeeper-0.{{ .Release.Name }}-zookeeper-headless.{{ .Release.Namespace }}:2181,{{ .Release.Name }}-zookeeper-1.{{ .Release.Name }}-zookeeper-headless.{{ .Release.Namespace }}:2181,{{ .Release.Name }}-zookeeper-2.{{ .Release.Name }}-zookeeper-headless.{{ .Release.Namespace }}:2181'
    {{- end }}
  K8S_ZK_SESSION_TIMEOUT: '{{ .Values.c3Cluster.zookeeperClient.maxSessionTimeout }}'
  K8S_ZK_USERNAME: '{{ .Values.c3Cluster.zookeeperClient.username }}'
  K8S_ZK_PASSWORD: '{{ .Values.c3Cluster.zookeeperClient.password }}'
  {{ if .Values.c3Cluster.zookeeperClient.enableTls }}K8S_ZK_ENABLE_TLS: '{{ .Values.c3Cluster.zookeeperClient.enableTls }}'{{- end }}
  {{ if .Values.c3Cluster.zookeeperClient.trustStorePath }}K8S_ZK_TRUSTSTORE: '{{ .Values.c3Cluster.zookeeperClient.trustStorePath }}'{{- end }}
  {{ if .Values.c3Cluster.zookeeperClient.trustStorePassword }}K8S_ZK_TS_PWD: '{{ .Values.c3Cluster.zookeeperClient.trustStorePassword }}'{{- end }}

  #
  # JVM Memory Configuration
  #
  {{ if .Values.c3Cluster.resources.limits -}}
  CONTAINER_MEMORY: '{{ .Values.c3Cluster.resources.limits.memory }}'
  {{- end }}
  JVM_MIN_MEM_FRACTION: '{{ .Values.c3Cluster.jvmMinMemFraction }}'
  JVM_MAX_MEM_FRACTION: '{{ .Values.c3Cluster.jvmMaxMemFraction }}'
  JVM_MIN_HEAP_ABSOLUTE: '{{ .Values.c3Cluster.jvmMinHeapAbsolute }}'
  JVM_MAX_HEAP_ABSOLUTE: '{{ .Values.c3Cluster.jvmMaxHeapAbsolute }}'
  JVM_ARGS: '{{ .Values.c3Cluster.jvmArgs }}'

  C3_DEBUG: '{{ .Values.c3Cluster.launchOptions.debug }}'
  C3_DEBUG_MEM: '{{ .Values.c3Cluster.launchOptions.debugMem }}'
  C3_DRY_RUN: '{{ .Values.c3Cluster.launchOptions.dryRun }}'
  C3_GC_LOG: '{{ .Values.c3Cluster.launchOptions.gcLog }}'
  C3_PROFILE: '{{ .Values.c3Cluster.launchOptions.profile }}'
  C3_SUSPEND: '{{ .Values.c3Cluster.launchOptions.suspend }}'
  C3_VERBOSE: '{{ .Values.c3Cluster.launchOptions.verbose }}'
  C3_APPS_ROOT: "{{ .Values.c3Cluster.c3AppsRoot }}"

  CLUSTER_NAME: '{{ template "c3Cluster.clusterName" . }}'
  # TODO n6eh4 What is C3_IMAGE_VERSION used for? Do we need it?
  C3_IMAGE_VERSION: '{{ .Values.c3Cluster.image.tag }}'
  C3_INSECURE_ACCESS: '{{ .Values.c3Cluster.insecureAccess }}'
  K8S_CONTROL_CLUSTER: '{{ template "c3Cluster.clusterName" . }}'

  #
  # Config and Vault Path for Config Framework
  #
  K8S_CONFIG_FS_ROOT: '{{ .Values.c3Cluster.externalVault.configRoot | default "file:///usr/local/share/c3/server/config" }}'
  K8S_CONFIG_FS_OWNER: '{{ .Values.c3Cluster.externalVault.configOwner | default "c3dev" }}'
  K8S_CONFIG_FS_REGION: '{{ .Values.c3Cluster.externalVault.configRegion | default "us-west-2" }}'
  K8S_VAULT_FS_ROOT: '{{ .Values.c3Cluster.externalVault.vaultRoot | default "file:///usr/local/share/c3/server/vault" }}'
  K8S_VAULT_FS_REGION: '{{ .Values.c3Cluster.externalVault.vaultRegion | default "us-west-2" }}'

  K8S_CLOUD_REGION: '{{ .Values.c3Cluster.aws.region }}'
  K8S_USE_MACHINE_CREDS: '{{ .Values.c3Cluster.aws.useMachineCreds }}'
  K8S_CLUSTER_CLOUD_SECURITY_ID: '{{ .Values.c3Cluster.aws.cloudSecurityId }}'
  K8S_ARTIFACT_S3_BUCKET_REGION: '{{ .Values.c3Cluster.aws.artifactS3BucketRegion }}'
  K8S_ARTIFACT_S3_BUCKET: '{{ .Values.c3Cluster.aws.artifactS3Bucket }}'
  K8S_CLOUD_ACCESS_KEY: '{{ .Values.c3Cluster.aws.accessKey }}'
  K8S_CLOUD_SECRET_KEY: '{{ .Values.c3Cluster.aws.secretKey }}'
  K8S_CLOUD_TEST_REGION: '{{ .Values.c3Cluster.aws.testRegion }}'
  K8S_CLOUD_TEST_SECURITY_ID: '{{ .Values.c3Cluster.aws.testSecurityId }}'

  K8S_ENABLE_LOCAL_FILE_SYSTEM: '{{ .Values.c3Cluster.enableLocalFileSystem }}'

  #
  # Installation boot configuration location; the name of the environment variable is declared as
  # c3.server.boot.manager.BootManager.C3_INSTALLATION_CONFIGURATION_ENV_VAR_NAME
  #
  C3_INSTALLATION_CONFIGURATION: '{{ .Values.c3Cluster.configFramework.installationProjectionMountPath }}/{{ .Values.c3Cluster.configFramework.installationProjectionFileName }}'

  CHROME_SELENIUM_SERVICE: '{{ .Release.Name }}-selenium-chrome.{{ .Release.Namespace }}'
  FIREFOX_SELENIUM_SERVICE: '{{ .Release.Name }}-selenium-firefox.{{ .Release.Namespace }}'

  K8S_DOWNWARD_API_MOUNT_PATH: '{{ .Values.c3Cluster.downwardApi.mountPath }}'

  #
  # TODO PLAT-24035 (also in server-config.xml.app.template)
  #
  K8S_EXTERNAL_VAULT_KIND: '{{ .Values.c3Cluster.externalVault.kind }}'
  K8S_EXTERNAL_VAULT_URL: '{{ .Values.c3Cluster.externalVault.url }}'
  K8S_EXTERNAL_VAULT_AUTH: '{{ .Values.c3Cluster.externalVault.auth }}'
  K8S_EXTERNAL_VAULT_ROLE: '{{ .Values.c3Cluster.externalVault.role }}'
  MIGRATE_TO_VAULT: '{{ .Values.c3Cluster.externalVault.kind }}'
  K8S_EXTERNAL_VAULT_IS_CA: '{{ .Values.c3Cluster.externalVault.isClusterCA }}'
  K8S_EXTERNAL_VAULT_ACCESS_TOKEN_DIR: '{{ .Values.c3Cluster.externalVault.vaultTokenDir }}'
  K8S_EXTERNAL_VAULT_MIGRATE_CONFIG_SOURCE: '{{ .Values.c3Cluster.configFramework.config.mountPath }}'
  K8S_EXTERNAL_VAULT_MIGRATE_VAULT_SOURCE: '{{ .Values.c3Cluster.configFramework.vault.mountPath }}'
  {{- if .Values.c3Cluster.envVars }}
  BRANCH_NAME: '{{ .Values.c3Cluster.envVars.BRANCH_NAME }}'
  BUILD_URL: '{{ .Values.c3Cluster.envVars.BUILD_URL }}'
  BUILD_NUMBER: '{{ .Values.c3Cluster.envVars.BUILD_NUMBER }}'
  TEST_RETRY: '{{ .Values.c3Cluster.envVars.TEST_RETRY }}'
  ENABLE_JARVIS: '{{ .Values.c3Cluster.envVars.ENABLE_JARVIS }}'
  {{- end }}

  #
  # Conda
  #
  {{- if .Values.c3Cluster.conda }}
  {{ if .Values.c3Cluster.conda.channelUrls }}CONDA_CHANNEL_URLS: '{{ .Values.c3Cluster.conda.channelUrls | join "," }}'{{- end }}
  {{ if .Values.c3Cluster.conda.configFiles }}CONDA_CONFIG_FILES: '{{ .Values.c3Cluster.conda.configFiles | join "," }}'{{- end }}
  {{- end }}
  #
  # pip
  #
  {{- if .Values.c3Cluster.pip }}
  {{ if .Values.c3Cluster.pip.indexUrl }}PIP_INDEX_URL: '{{ .Values.c3Cluster.pip.indexUrl }}'{{- end }}
  {{ if .Values.c3Cluster.pip.configFiles }}PIP_CONFIG_FILES: '{{ .Values.c3Cluster.pip.configFiles | join "," }}'{{- end }}
  {{- end }}
  #
  # npm
  #
  {{- if .Values.c3Cluster.npm }}
  {{ if .Values.c3Cluster.npm.registryUrl }}NPM_REGISTRY_URL: '{{ .Values.c3Cluster.npm.registryUrl }}'{{- end }}
  {{ if .Values.c3Cluster.npm.configFiles }}NPM_CONFIG_FILES: '{{ .Values.c3Cluster.npm.configFiles | join "," }}'{{- end }}
  {{- end }}
  #
  # proxy
  #
  {{- if .Values.c3Cluster.proxy }}
  {{ if .Values.c3Cluster.proxy.noProxy }}NO_PROXY: '{{ .Values.c3Cluster.proxy.noProxy }}'{{- end }}
  {{ if .Values.c3Cluster.proxy.httpProxy }}HTTP_PROXY: '{{ .Values.c3Cluster.proxy.httpProxy }}'{{- end }}
  {{ if .Values.c3Cluster.proxy.httpsProxy }}HTTPS_PROXY: '{{ .Values.c3Cluster.proxy.httpsProxy }}'{{- end }}
  {{- end}}
  #
  # tls
  #
  K8S_TLS_ENABLED: '{{ .Values.c3Cluster.tls.enabled }}'
  K8S_TS_PATH: '{{ .Values.c3Cluster.tls.trustStorePath }}'
  K8S_TS_PASS: '{{ .Values.c3Cluster.tls.trustStorePassword }}'
  K8S_KS_PATH: '{{ .Values.c3Cluster.tls.keyStorePath }}'
  K8S_KS_PASS: '{{ .Values.c3Cluster.tls.keyStorePassword }}'
  K8S_CERTS_DIR: '{{ .Values.c3Cluster.tls.certsDir }}'
  #
  # web security
  #
  K8S_CORS_ENABLED: '{{ .Values.c3Cluster.websecurity.corsEnabled }}'
  K8S_VARY_HEADER: '{{ .Values.c3Cluster.websecurity.varyHeader }}'
  K8S_CC_HEADER_ENABLED: '{{ .Values.c3Cluster.websecurity.cacheControlHeaderEnabled }}'
  K8S_XSS_HEADER_ENABLED: '{{ .Values.c3Cluster.websecurity.xssHeaderEnabled }}'
  K8S_XSS_BLOCKMODE_ENABLED: '{{ .Values.c3Cluster.websecurity.xssBlockModeEnabled }}'
  K8S_XFO_HEADER: '{{ .Values.c3Cluster.websecurity.xFrameOptionsHeader }}'
  K8S_CSP_HEADER: '{{ .Values.c3Cluster.websecurity.cspHeader }}'
