type BundlerMeasurements = {
    allProcessesStart?: number;
    allProcessesEnd?: number;
    allProcessesTotal?: number;
    npmInstallTotal?: number;
    setupWorkDirStart?: number;
    setupWorkDirEnd?: number;
    setupWorkDirTotal?: number;
    repoWatcherStart?: number;
    repoWatcherEnd?: number;
    repoWatcherTotal?: number;
    bundlerStart?: number;
    bundlerEnd?: number;
    bundlerTotal?: number;
    maxMemory?: number;
    isIncrementalFileUpdate?: boolean;
    fileName?: string;
    loaderType?: string;
};
export default BundlerMeasurements;
