{
 "title": "Avg. Node Runtime",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Avg. Node Runtime",
   "type": "gauge",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_csv_seconds_sum/info_csv_seconds_count",
     "legendFormat": "CSV Node"
    },
    {
     "expr": "info_h2o_isolation_forest_seconds_sum/info_h2o_isolation_forest_seconds_count",
     "legendFormat": "Isolation Forest Node"
    },
    {
     "expr": "info_h2o_kMeans_seconds_sum/info_h2o_kMeans_seconds_count",
     "legendFormat": "K-Means Node"
    },
    {
     "expr": "info_h2o_automl_classifier_seconds_sum/info_h2o_automl_classifier_seconds_count ",
     "legendFormat": "Model Search Classifier"
    },
    {
     "expr": "info_textSplit_seconds_sum/info_textSplit_seconds_count",
     "legendFormat": "Text Split Node"
    },
    {}
   ]
  },
  { "title": "CSV FileUpload Runtime Stats ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CSV File Upload Duration Distribution.",
   "type": "bargauge",
   "description": "The x axis is the range in seconds and the y axis is the total no of file uploads. there are 3 files that take between 0.1-0.25 seconds to upload.",
   "gridPos": { "h": 20, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "info_csv_seconds_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "CSV File Uploads less than 2.5s",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_csv_seconds_bucket{le=\"2.5\"}"
    }
   ]
  },
  {
   "title": "Percentage of CSV File Uploads less than 2.5s",
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_csv_seconds_bucket{le= \"2.5\"} / ignoring (le) info_csv_seconds_count"
    }
   ]
  },
  {
   "title": "Number of CSV file uploads more than 2.5s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "info_csv_seconds_count - ignoring (le) info_csv_seconds_bucket{le = \"2.5\"}"
    }
   ]
  },
  {
   "title": "Percentage of CSV File Uploads more than 2.5s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(info_csv_seconds_count - ignoring (le) info_csv_seconds_bucket{le=\"2.5\"})/info_csv_seconds_count\n"
    }
   ]
  }
 ]
}