# Default values for a C3 Cluster chart.
# This is a YAML-formatted file.

#
# These configuration values will be applied to persistence components deployed by this chart, when this chart is
# declared as a dependency for other top-level charts (c3-cluster, c3-builder). These values can be overridden
# from dependent chart's values.yaml, but that is normally not necessary.
#

postgresql:
  image:
    #
    # We need PostgreSQL with spatial and geographic objects extension, otherwise integration tests will fail
    #
    registry: docker.io
    repository: postgres
    tag: 11-alpine
    pullPolicy: IfNotPresent 

  #
  # This initializes PostgreSQL admin user password. The value is hardcoded in the C3 code.
  # TODO PLAT-25496
  #
  postgresqlPassword: "c3postgres"

  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 10

  volumePermissions:
    enabled: false
    image:
      registry: docker.io
      repository: bitnami/minideb
      #
      # We settle on a specific version, and we do not use "latest" as suggested by the underlying chart
      # because there is no good reason to pull this image every the PostgreSQL pod is created
      #
      tag: bookworm
      pullPolicy: IfNotPresent 

cassandra:
  image:
    repo: docker.io
    repository: cassandra
    tag: 3.11
    pullPolicy: IfNotPresent 
  config:
    cluster_size: 1
    seed_size: 1
    start_rpc: true
  env:
    # Note: -Djava.rmi.server.hostname=0.0.0.0 causes "Connection refused to host: 0.0.0.0" on the Cassandra server so don't use it
    JVM_EXTRA_OPTS: "-Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.rmi.port=7199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"

  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 10

#
# HashiCorp Vault settings:
#
# We use Developer mode: auto initializes and unseals the vault; uses in memory storage rather than disk (PV).
#
# Set vault.enabled to true to enable Vault.
#
vault:
  enabled: false
  server:
    dev:
      enabled: true
    image:
      repository: docker.io/hashicorp/vault
      tag: "1.4.0"
  injector:
    enabled: false
