/**
 * Configuration keys and environment variables
 *
 * All environment variable names, configuration keys, and default values.
 */
export declare const ENV_VARS: {
    readonly NODE_ENV: "NODE_ENV";
    readonly USER: "USER";
    readonly HOSTNAME: "HOSTNAME";
    readonly HOME: "HOME";
    readonly SHELL: "SHELL";
    readonly EDITOR: "EDITOR";
    readonly VISUAL: "VISUAL";
    readonly USERPROFILE: "USERPROFILE";
    readonly APPDATA: "APPDATA";
    readonly LOCALAPPDATA: "LOCALAPPDATA";
    readonly COMSPEC: "COMSPEC";
    readonly LSH_API_ENABLED: "LSH_API_ENABLED";
    readonly LSH_API_PORT: "LSH_API_PORT";
    readonly LSH_API_KEY: "LSH_API_KEY";
    readonly LSH_JWT_SECRET: "LSH_JWT_SECRET";
    readonly LSH_ALLOW_DANGEROUS_COMMANDS: "LSH_ALLOW_DANGEROUS_COMMANDS";
    readonly LSH_SAAS_API_PORT: "LSH_SAAS_API_PORT";
    readonly LSH_SAAS_API_HOST: "LSH_SAAS_API_HOST";
    readonly LSH_CORS_ORIGINS: "LSH_CORS_ORIGINS";
    readonly LSH_SECRETS_KEY: "LSH_SECRETS_KEY";
    readonly LSH_MASTER_KEY: "LSH_MASTER_KEY";
    readonly LSH_LOCAL_STORAGE_QUIET: "LSH_LOCAL_STORAGE_QUIET";
    readonly LSH_V1_COMPAT: "LSH_V1_COMPAT";
    readonly DISABLE_IPFS_SYNC: "DISABLE_IPFS_SYNC";
    readonly LSH_LOG_LEVEL: "LSH_LOG_LEVEL";
    readonly LSH_LOG_FORMAT: "LSH_LOG_FORMAT";
    readonly NO_COLOR: "NO_COLOR";
    readonly LSH_ENABLE_WEBHOOKS: "LSH_ENABLE_WEBHOOKS";
    readonly WEBHOOK_PORT: "WEBHOOK_PORT";
    readonly GITHUB_WEBHOOK_SECRET: "GITHUB_WEBHOOK_SECRET";
    readonly GITLAB_WEBHOOK_SECRET: "GITLAB_WEBHOOK_SECRET";
    readonly JENKINS_WEBHOOK_SECRET: "JENKINS_WEBHOOK_SECRET";
    readonly DATABASE_URL: "DATABASE_URL";
    readonly SUPABASE_URL: "SUPABASE_URL";
    readonly SUPABASE_ANON_KEY: "SUPABASE_ANON_KEY";
    readonly REDIS_URL: "REDIS_URL";
    readonly MONITORING_API_PORT: "MONITORING_API_PORT";
    readonly STRIPE_SECRET_KEY: "STRIPE_SECRET_KEY";
    readonly STRIPE_WEBHOOK_SECRET: "STRIPE_WEBHOOK_SECRET";
    readonly STRIPE_PRICE_PRO_MONTHLY: "STRIPE_PRICE_PRO_MONTHLY";
    readonly STRIPE_PRICE_PRO_YEARLY: "STRIPE_PRICE_PRO_YEARLY";
    readonly STRIPE_PRICE_ENTERPRISE_MONTHLY: "STRIPE_PRICE_ENTERPRISE_MONTHLY";
    readonly STRIPE_PRICE_ENTERPRISE_YEARLY: "STRIPE_PRICE_ENTERPRISE_YEARLY";
    readonly RESEND_API_KEY: "RESEND_API_KEY";
    readonly EMAIL_FROM: "EMAIL_FROM";
    readonly BASE_URL: "BASE_URL";
};
export declare const DEFAULTS: {
    readonly VERSION: "0.5.1";
    readonly API_PORT: 3030;
    readonly SAAS_API_PORT: 3031;
    readonly WEBHOOK_PORT: 3033;
    readonly MONITORING_API_PORT: 3031;
    readonly MONITORING_PORT: 3000;
    readonly DEFAULT_HOST: "0.0.0.0";
    readonly DEFAULT_CORS_ORIGINS: readonly ["*"];
    readonly REDIS_URL: "redis://localhost:6379";
    readonly DATABASE_URL: "postgresql://localhost:5432/cicd";
    readonly STRIPE_API_URL: "https://api.stripe.com/v1";
    readonly RESEND_API_URL: "https://api.resend.com/emails";
    readonly LSH_APP_URL: "https://app.lsh.dev";
    readonly LSH_DOCS_URL: "https://docs.lsh.dev";
    readonly KUBO_RELEASES_URL: "https://api.github.com/repos/ipfs/kubo/releases/latest";
    readonly DEFAULT_EMAIL_FROM: "noreply@lsh.dev";
    readonly CHECK_INTERVAL_MS: 2000;
    readonly REQUEST_TIMEOUT_MS: 10000;
    readonly DAEMON_RESTART_DELAY_MS: 1000;
    readonly JOB_TIMEOUT_1H_MS: 3600000;
    readonly JOB_TIMEOUT_5M_MS: 300000;
    readonly JOB_TIMEOUT_1M_MS: 60000;
    readonly JOB_TIMEOUT_2H_MS: 7200000;
    readonly MAX_BUFFER_SIZE_BYTES: number;
    readonly MAX_LOG_SIZE_BYTES: number;
    readonly MAX_COMMAND_LENGTH: 10000;
    readonly SOCKET_BUFFER_SIZE: 1024;
    readonly MAX_EVENTS_LIMIT: 100;
    readonly MAX_HISTORY_SIZE: 10000;
    readonly HISTORY_SAVE_INTERVAL_MS: 30000;
    readonly MAX_COMMAND_CHAINS: 5;
    readonly MAX_PIPE_USAGE: 3;
    readonly REDIS_CACHE_EXPIRY_SECONDS: 3600;
    readonly METRICS_RETENTION_SECONDS: number;
    readonly CLOUD_CONFIG_SYNC_INTERVAL_MS: 60000;
    readonly HISTORY_SYNC_INTERVAL_MS: 30000;
    readonly MAX_RECORDS_PER_JOB: 1000;
    readonly MAX_TOTAL_RECORDS: 50000;
    readonly METRICS_RETENTION_DAYS: 90;
    readonly DEFAULT_SHELL_UNIX: "/bin/sh";
    readonly DEFAULT_SHELL_WIN: "cmd.exe";
    readonly DEFAULT_EDITOR: "vi";
};
