# Default values for the C3 Selenium chart
# This is a YAML-formatted file.

#
# These configuration values will be applied to Selenium components deployed by this chart, when this chart is
# declared as a dependency for other top-level charts (c3-builder, c3-tester). These values can be overridden
# from dependent chart's values.yaml, but that is normally not necessary.
#

#
# The C3_SERVER_ROOT value. As there is no way to come up with a default to that, or at least a default that is not
# brittle, we require that a value is passed by the calling layer
#

c3ServerRoot: 'C3_SERVER_ROOT_TO_BE_SET_DURING_INSTALLATION'

c3Selenium:
  chrome:
    image: 'ci-artifacts.c3.ai/selenium/standalone-chrome-debug'
    #
    # Normally it would not matter if the chrome ports and firefox ports (below) conflict, as they
    # apply to different pods. However, on Docker Desktop Kubernetes, the LoadBalancer service projects
    # both on the same local network stack and the will conflict. Addressed by overriding value in
    # mac.yaml
    #
    service:
      seleniumPort: 4444
      vncPort: 5900
      chromeDebuggingPort: 9222
  firefox:
    image: 'ci-artifacts.c3.ai/selenium/standalone-firefox-debug'
    #
    # Normally it would not matter if the chrome (above) ports and firefox ports conflict, as they
    # apply to different pods. However, on Docker Desktop Kubernetes, the LoadBalancer service projects
    # both on the same local network stack and the will conflict. Addressed by overriding value in
    # mac.yaml
    #
    service:
      seleniumPort: 4444
      vncPort: 5900

  #
  # Configuration of a local directory (for single-node Kubernetes clusters) or an NFS share (for multi-node Kubernetes
  # clusters) that will be projected into the selenium pod. For semantics, see below:
  #
  # TODO PLAT-24900
  #
  sharedFileSystem:
    #
    # The name of the local filesystem directory that will be mounted by the selenium pod and projected as shared
    # directory. Using a local file system directory to provide shared file system space across cluster will only work
    # for single-node Kubernetes clusters (minikube). For multi-node clusters, use an NFS-based solution.
    #
    local: /tmp
    #
    # TODO PLAT-24900 add NFS support
    # nfs:
    #  server:
    #  path:
    #
    # The name of the selenium pod mount path: the local filesystem directory specified as "local" or the NFS share will
    # be projected in the selenium pod as "mountPath"
    #
    mountPath: '/c3-cluster-shared'
    subPath: 'c3-cluster-shared'
