{{- if .Values.c3Cluster.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: c3-ingress
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  name: {{ template "c3Cluster.clusterName" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.c3Cluster.ingress.class }}
    {{- if .Values.c3Cluster.ingress.annotations }}
    {{- range $annotation, $value := .Values.c3Cluster.ingress.annotations }}
    {{ $annotation }}: {{ $value | quote -}}
    {{ end }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.c3Cluster.ingress.serviceName }}
                port:
                  number: {{ .Values.c3Cluster.ingress.servicePort }}
#  rules:
#  {{- if .Values.c3Cluster.ingress.rules }}
#  {{- range $rule := .Values.c3Cluster.ingress.rules }}
#  - host: {{ $rule.host | quote }}
#    http:
#      paths:
#        - path: /
#          backend:
#            serviceName: {{ $rule.backend.serviceName }}
#            servicePort: {{ $rule.backend.servicePort }}
#  {{- end }}
#  {{- end }}

  {{- if .Values.c3Cluster.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.c3Cluster.ingress.tls.secret.name }}
      {{- range $host := .Values.c3Cluster.ingress.tls.hosts }}
      hosts:
        - {{ $host }}
      {{- end }}
  {{- end }}
{{- end}}
