apiVersion: v1
kind: Secret
metadata:
  name: splunk-server-password
{{/*  annotations:*/}}
{{/*    "helm.sh/resource-policy": no-upgrade-existing*/}}
  labels:
    app: {{ .Release.Name }}-splunk-server
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  {{- if .Values.c3splunk.password }}
  password: {{ .Values.c3splunk.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
