apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-splunk-server
    release: {{ .Release.Name }}
  name: splunk
spec:
  ports:
  - name: web
    port: 8000
    targetPort: 8000
  - name: hec
    port: 8088
    targetPort: 8088
  - name: rest
    port: 8089
    targetPort: 8089
  - name: index-receiver
    port: 9997
    targetPort: 9997
  - name: app-server
    port: 8065
    targetPort: 8065
  selector:
    app: {{ .Release.Name }}-splunk-server
    release: {{ .Release.Name }}
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 34.232.23.54/32   # open vpn
  - 34.231.113.223/32 # office
  - 12.226.154.130/32 # office
  - 34.219.152.22/32  # jenkins-cloud-master
  - 35.163.37.31/32   # jenkins-cloud-worker
