apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-c3cli
spec:
  replicas: {{ default 1 .Values.c3cli.replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-c3cli
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-c3cli
        release: {{ .Release.Name }}-c3cli
    spec:
      securityContext:
        runAsUser: {{ .Values.c3cli.security.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.c3cli.security.podSecurityContext.runAsGroup }}
      containers:
        - name: {{ .Release.Name }}-c3cli
          image: '{{ .Values.c3cli.image.registry }}/{{ .Values.c3cli.image.repository }}:{{ .Values.c3cli.image.tag }}'
          imagePullPolicy: IfNotPresent
          resources: {{ toYaml .Values.c3cli.resources | nindent 12 }}
          command:
            - /bin/sh
            - /scripts/run.sh
          env:
            - name: C3SERVER_URL
              value: {{ template "c3cli.clusterEndpoint" . }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - /scripts/readiness.sh
            initialDelaySeconds: 60
            timeoutSeconds: 15
            periodSeconds: 20
            failureThreshold: 1
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: ephemeral-empty-dir
              mountPath: /cli
              subPath: cli
            - name: ephemeral-empty-dir
              mountPath: /c3
              subPath: c3
            - name: ephemeral-empty-dir
              mountPath: /.c3
              subPath: .c3
            - name: ephemeral-empty-dir
              mountPath: /.npm
              subPath: .npm
            - name: ephemeral-empty-dir
              mountPath: /.config
              subPath: .config
            - name: ephemeral-empty-dir
              mountPath: /src
              subPath: src
      volumes:
        - name: ephemeral-empty-dir
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-c3cli-config
